@LearningASP_HostAddress = http://localhost:5229

POST {{LearningASP_HostAddress}}/auth/register
Content-Type: application/json

{
  "Email": "johny.smith@google.com",
  "Password": "mypassword",
  "FirstName": "Johny",
  "LastName": "Smith"
}

### 

POST {{LearningASP_HostAddress}}/auth/register
Content-Type: application/json

{
  "Email": "johnyaa.smith@google.com",
  "Password": "mypassword",
  "FirstName": "Johny"
}

###

POST {{LearningASP_HostAddress}}/auth/register
Content-Type: application/json

{
  "Email": "jenny.smith@google.com",
  "Password": "mypassword",
  "FirstName": "Jenny",
  "LastName": "Smith"
}

###

POST {{LearningASP_HostAddress}}/auth/login
Content-Type: application/json

{
  "Email": "johny.smith@google.com",
  "Password": "mypassword"
}

###
@Auth = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiam9obnkuc21pdGhAZ29vZ2xlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkpvaG55IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6IlNtaXRoIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsImV4cCI6MTcyNjkxMDQ0NSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0._OILPNdzEA3tIEx2WcX05RvFaFq81efxgNGe8UQudrg


###

GET {{LearningASP_HostAddress}}/auth/user
Authorization: {{Auth}}

###

GET {{LearningASP_HostAddress}}/secret
Authorization: {{Auth}}


###

GET {{LearningASP_HostAddress}}/user
Content-Type: application/json
Authorization: {{Auth}}
