# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: react

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: client/package-lock.json
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies  
        run: npm ci
      - name: Build  
        run: npm run build
      - name: Lint
        run: npm run lint --max-warnings=0
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: client/dist
#      - name: Test  
#        run: npm test
  deploy:
    
    runs-on: ubuntu-latest
    needs: build
    environment: Master
      
    env:
      VITE_API_URL: ${{ vars.VITE_API_URL }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
